import { Metadata } from 'next'
import styles from './layout.module.css'
import './globals.css'
import { Open_Sans } from 'next/font/google'
import { Header } from '@/components/Header/Header'
import { Sidebar } from '@/components/Sidebar/Sidebar'
import { Footer } from '@/components/Footer/Footer'
import { Up } from '@/components/Up/Up'

const inter = Open_Sans({ subsets: ['latin'] })

// Эти метаданные будут видны когда мы на главной
export const metadata: Metadata = {
	title: 'Наш проект',
	description: 'Generated by create next app',
	openGraph: {
		images: [
		  {
		    url: 'https://images.unsplash.com/photo-1599137258505-8871bd07cbbb?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8dGliZXR8ZW58MHx8MHx8fDA%3D',
		    width: 800,
		    height: 630,
		  },
		],
		url: 'https://timofeev-28.ru',
		locale: 'ru_RU',
		type: 'website',
	}
}

export default function RootLayout({children}: {children: React.ReactNode}) {

	return (
		<html lang="ru">
			<head>
			</head>
			<body className={inter.className}>
				<div className={styles.wrapper}>
					<Header className={styles.header} />
					<Sidebar className={styles.sidebar} />
					<main className={styles.body}>
						{children}
					</main>
					<Footer className={styles.footer} role='main'/>
					<Up />
				</div>
			</body>
		</html>
	)
}
